# Centralized logging configuration using YAML
version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  request_handler:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: logs/requests.log
  result_handler:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: logs/results.log
  error_handler:
    class: logging.FileHandler
    level: ERROR
    formatter: simple
    filename: logs/errors.log
loggers:
  request_logger:
    handlers: [request_handler]
    level: INFO
    propagate: no
  result_logger:
    handlers: [result_handler]
    level: INFO
    propagate: no
  error_logger:
    handlers: [error_handler]
    level: ERROR
    propagate: no
root:
  level: NOTSET
  handlers: []